# Generated by Django 2.2.12 on 2020-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='区'),
        ),
    ]
