# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('create_user_id', models.IntegerField(default=0, verbose_name='订单创建人')),
                ('order_status', models.IntegerField(default=0, verbose_name='订单状态')),
                ('receiver', models.CharField(default='', max_length=128, verbose_name='收货人')),
                ('receiver_tel', models.CharField(default='', max_length=128, verbose_name='收货人电话')),
                ('receiver_address', models.CharField(default='', max_length=128, verbose_name='收货人地址')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('arrive_time', models.DateTimeField(auto_now_add=True, verbose_name='到货时间')),
                ('cancel_time', models.DateTimeField(auto_now_add=True, verbose_name='取消时间')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
            },
        ),
    ]
