# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=128, verbose_name='分类名')),
                ('category', models.CharField(default='', max_length=128, verbose_name='大类别')),
            ],
            options={
                'verbose_name': 'ProductClass',
                'verbose_name_plural': 'ProductClass',
            },
        ),
    ]
