# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总余额')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用余额')),
                ('recharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充值金额')),
                ('consume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消费金额')),
            ],
            options={
                'verbose_name': 'UserWallet',
                'verbose_name_plural': 'UserWallet',
            },
        ),
    ]
