# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201123_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'ordertest', 'verbose_name_plural': 'ordertest'},
        ),
    ]
