# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_words', models.CharField(default='', max_length=128, verbose_name='查询关键字')),
                ('search_user', models.IntegerField(default=0, verbose_name='查询人')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
            ],
            options={
                'verbose_name': 'SearchHistory',
                'verbose_name_plural': 'SearchHistory',
            },
        ),
    ]
