# Generated by Django 2.2.12 on 2020-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0003_rotation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='img',
            field=models.FileField(blank=True, default='', upload_to='productImages'),
        ),
    ]
