# Generated by Django 2.2.12 on 2020-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0004_rotation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='img',
            field=models.FileField(blank=True, default='', upload_to='image'),
        ),
    ]
