# Generated by Django 2.2.12 on 2020-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0005_auto_20201222_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotation',
            name='img',
        ),
        migrations.AlterField(
            model_name='rotation',
            name='img_path',
            field=models.FileField(blank=True, default='', upload_to='image'),
        ),
    ]
