# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='轮播图标题')),
                ('img_path', models.CharField(default='', max_length=128, verbose_name='图片地址')),
                ('link', models.CharField(default='', max_length=128, verbose_name='图片链接')),
                ('remark', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Rotation',
                'verbose_name_plural': 'Rotation',
            },
        ),
    ]
