# Generated by Django 2.2.12 on 2020-12-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cart_id',
            field=models.IntegerField(default=0, verbose_name='cartID'),
        ),
    ]
