# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0, verbose_name='商品ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('modify_user', models.IntegerField(default=0, verbose_name='Modify_user_ID')),
            ],
            options={
                'verbose_name': 'PriceHistory',
                'verbose_name_plural': 'PriceHistory',
            },
        ),
    ]
