# Generated by Django 2.2.12 on 2020-11-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('comment', models.CharField(max_length=800, verbose_name='评论')),
                ('order_id', models.IntegerField(verbose_name='orderID')),
                ('img', models.FileField(default='', upload_to='myImages')),
            ],
        ),
    ]
