# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_comment',
            options={'verbose_name': 'User_Comment', 'verbose_name_plural': 'User_Comment'},
        ),
    ]
