# Generated by Django 2.2.12 on 2020-11-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_comment', '0002_auto_20201126_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comment',
            name='star',
            field=models.IntegerField(default=0, verbose_name='star'),
        ),
        migrations.AddField(
            model_name='user_comment',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
    ]
