# Generated by Django 2.2.12 on 2020-12-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(default='', max_length=30, null=True, verbose_name='收货人')),
                ('province', models.CharField(default='', max_length=64, null=True, verbose_name='省')),
                ('city', models.CharField(default='', max_length=64, null=True, verbose_name='市')),
                ('district', models.CharField(default='', max_length=64, null=True, verbose_name='区')),
                ('detail_address', models.CharField(default='', max_length=128, null=True, verbose_name='详细地址')),
                ('TELEPHONE', models.CharField(default='', max_length=64, null=True, verbose_name='电话')),
                ('email', models.CharField(default='', max_length=64, null=True, verbose_name='邮箱')),
                ('remark', models.CharField(default='', max_length=64, null=True, verbose_name='别名(公司, 家里, 父母家)')),
            ],
            options={
                'verbose_name': 'UserAddress',
                'verbose_name_plural': 'UserAddress',
            },
        ),
    ]
