# Generated by Django 2.2.12 on 2020-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_ids', models.CharField(default='', max_length=30, verbose_name='类别ID')),
                ('img', models.FileField(default='', upload_to='productImages')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('product_name', models.CharField(default='', max_length=128, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品价格')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存数量')),
                ('productor', models.CharField(default='', max_length=128, verbose_name='生产商')),
                ('author', models.CharField(default='', max_length=128, verbose_name='生产者')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
