# Generated by Django 2.2.12 on 2020-11-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201128_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='生产者'),
        ),
        migrations.AlterField(
            model_name='product',
            name='class_ids',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='类别ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, default='', upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.FileField(blank=True, default='', upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.FileField(blank=True, default='', upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.FileField(blank=True, default='', upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.FileField(blank=True, default='', upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productor',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='生产商'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(blank=True, default=0, verbose_name='状态'),
        ),
    ]
